config/routes.rb
Rails.application.routes.draw do

  root to: "meal_postings#index"

  resources :users, except: [:index] do
    resources :meal_postings
    resources :user_ratings, except: [:show, :edit]
  end

  resources :meal_postings do
    resources :categories, only: [:show]
    resources :reservations
    resources :meal_ratings, except: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # COMMENTED OUT FOR NOW #
    # get '/login', to: 'posting#index'

    resources :postings, only: [:index, :new, :create]


    # CREATED FOR SESSIONS
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
    put '/user/location' => 'sessions#update'

    # CREATED FOR MEAL POSTING CATEGORIES
    put '/meal_postings/categories/:id' => 'meal_postings#category', :as => :meals_category

    # CREATED TO SHOW HOSTS / USERS THEIR CURRENT RESERVATIONS / REQUESTS
    get '/reservations' => 'reservations#index'#, :as => :user_reservations
    #CREATED TO SHOW HOSTS THEIR RESERVATIONS TO OTHER HOSTS
    get '/reservations/outgoing' => 'reservations#outgoingreservations'
    #TO CHANGE TO ACCEPTED / REJECTED
    put '/reservations/:id/accept' => 'reservations#accept'
    put '/reservations/:id/reject' => 'reservations#reject'

    ############## FOR hostdelete and userdelete ###############
    put '/reservations/:id/hostdelete' => 'reservations#hostdelete'
    put '/reservations/:id/userdelete' => 'reservations#userdelete'
    put '/reservations/outgoing/:id/userdelete' => 'reservations#userdelete'

    delete 'reservations/:id/destroy' => 'reservations#destroy'
    put '/reservations/:id/order' => 'reservations#order', :as => :reservation_order

    # TO CREATE A NEW RESERVATION
    post '/reservations/create/:id' => 'reservations#create', :as => :create_reservation

    # CREATED FOR A MEALPOSTING REVIEWS
    get '/meal_posting/:id/reviews' => 'meal_postings#meal_posting_reviews', :as => :meal_posting_reviews

    # CREATED FOR ANALYTICS
    get '/analytics' => 'analytics#index', :as => :analytics
end

app/models/meal_posting.rb
class MealPosting < ApplicationRecord

  attr_accessor :image

  mount_uploader :image, AvatarUploader

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :meal_ratings
  has_many :media
  has_many :reservations

  validates :base_time, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :servings, presence: true, :numericality => { :greater_than => 0}
  validates :cost, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :date, presence: true
  validate  :end_time_cannot_be_earlier_than_start_time
  validate  :date_cannot_be_in_the_past

  def end_time_cannot_be_earlier_than_start_time

    if end_time
      if base_time > end_time
        errors.add(:end_time, "can't be earlier than the start time")
      end
    end
  end

  def date_cannot_be_in_the_past
    if date
      if date < Date.today
        errors.add(:date, "can't be set in the past")
      end
    end
  end
end

app/controllers/meal_postings_controller.rb
class MealPostingsController < ApplicationController
  before_action :set_meal_posting, only: [:show, :edit, :update, :destroy]

  # GET /meal_postings
  # GET /meal_postings.json
  def index
    @meal_postings = MealPosting.all
    if params[:category]
      @meal_postings = MealPosting.where("category_id = #{params[:id].to_i}")
    end

    if current_user_latitude
      m_lat = current_user_latitude.to_f
      m_lng = current_user_longitude.to_f
    else
      m_lat = 43.644881
      m_lng = -79.395208
    end

    @meal_postings = @meal_postings.sort {|a, b|
      a_lat = a.user.latitude
      a_lng = a.user.longitude
      b_lat = b.user.latitude
      b_lng = b.user.longitude
      distance_a = Math.sqrt((m_lat - a_lat) ** 2 + (m_lng - a_lng) ** 2)
      distance_b = Math.sqrt((m_lat - b_lat) ** 2 + (m_lng - b_lng) ** 2)
      distance_a <=> distance_b
    }


    @categories = Category.all
  end

  # GET /meal_postings/1
  # GET /meal_postings/1.json
  def show
    @user = User.find(@meal_posting.user_id)
    @usermeals = @user.meal_postings
    @reservation = Reservation.new
    @other_meal_ids = MealPosting.where("user_id = ? AND id != ?", @meal_posting.user_id, @meal_posting.id).ids
    @ordered_meal_ids = @other_meal_ids.unshift(@meal_posting.id)
  end

  #GET /meal_posting/1/reviews
  def meal_posting_reviews
    @meal_posting = MealPosting.find(params[:id])
    @review = MealRating.new
  end


  def category
    redirect_to meal_postings_path(id: params[:id], category: true)
  end

  # GET /meal_postings/new
  def new
  # or params[:user_id].to_i

    # Stops users with status "User" from accessing meal creation form by typing in URL
    if current_user.user_status == "User"
      redirect_to root_path
    else

      @meal_posting = MealPosting.new
      if current_user  != User.find(params[:user_id])
        if current_user
          redirect_to user_path(current_user.id)
        else
          redirect_to root_path
        end
      end

    end
  end

  # GET /meal_postings/1/edit
  def edit
  end

  # POST /meal_postings
  # POST /meal_postings.json
  def create
    @meal_posting = MealPosting.new(meal_posting_params)
    @meal_posting.user = current_user

    respond_to do |format|
      if @meal_posting.save
        format.html { redirect_to @meal_posting }#, notice: 'Meal posting was successfully created.' }
        format.json { render :show, status: :created, location: @meal_posting }
      else
        format.html { render :new }
        format.json { render json: @meal_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meal_postings/1
  # PATCH/PUT /meal_postings/1.json
  def update
    respond_to do |format|
      if @meal_posting.update(meal_posting_params)
        format.html { redirect_to @meal_posting }#, notice: 'Meal posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal_posting }
      else
        format.html { render :edit }
        format.json { render json: @meal_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_postings/1
  # DELETE /meal_postings/1.json
  def destroy
    @meal_posting.destroy
    redirect_to user_path(current_user.id)
    # respond_to do |format|
      # format.html { redirect_to meal_postings_url } #, notice: 'Meal posting was successfully destroyed.' }
      # format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal_posting
      @meal_posting = MealPosting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_posting_params
      params.require(:meal_posting).permit(
        :base_time,
        :end_time,
        :title,
        :description,
        :allergy_notice,
        :servings,
        :cost,
        :image,
        :category_id,
        :date
      )
    end


end

app/helpers/meal_postings_helper.rb
module MealPostingsHelper
end

app/views/meal_postings/_form.html.erb
<div class="create-meal-posting">
  <%= form_with(model: meal_posting, local: true) do |form| %>
    <% if meal_posting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(meal_posting.errors.count, "error") %> prohibited this meal posting from being saved:</h2>

        <ul>
        <% meal_posting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


  <table clas="new-meal-table">
      <tr>
      <div class="form-group">
        <th class="new-meal-field"><%= form.label :title %></th>
        <td><%= form.text_field :title, id: :meal_posting_title %></td>
      </div>
    </tr>
    <tr>
      <div class="form-group">
        <th class="new-meal-field"><%= form.label :description %></th>
        <td><%= form.text_area :description, id: :meal_posting_description %></td>
      </div>
    </tr>

    <tr>
      <div class="form-group">
        <th class="new-meal-field"><%= form.label :category %></th>
        <td><%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :name), { include_blank: true } %></td>
      </div>
    </tr>
    <tr>
      <div class="form-group">
        <th class="new-meal-field"><%= form.label :allergy_notice %></th>
        <td><%= form.text_field :allergy_notice, id: :meal_posting_allergy_notice %>  </td>
      </div>
    </tr>
    <tr>
      <div class="form-group">
        <th class="new-meal-field"><%= form.label :servings %></th>
        <td><%= form.number_field :servings, id: :meal_posting_servings %></td>
      </div>
    </tr>
    <tr>
      <div class="form-group">
        <th class="new-meal-field"><%= form.label :cost %></th>
        <td><%= form.number_field :cost, id: :meal_posting_cost %></td>
      </div>
    </tr>
    <tr>
      <div class="form-group">
        <th class="register-field"><%= form.label "Image: " %></th>
        <td><%= form.file_field :image, id: :meal_image %></td>
      </div>
    </tr>
    <tr>
      <div class="form-group">
        <th class="new-meal-field"><%= form.label :date %></th>
        <td><%= form.date_field :date, id: :meal_posting_date, min: Date.today %></td>
      </div>
    </tr>

    <tr>
      <div class="form-group">
        <th class="new-meal-field"><%= form.label :base_time %></th>
        <td><%= form.time_select :base_time, {
          ampm: true,
          ignore_date: true
        } %></td>
      </div>
    </tr>
      <tr>
      <div class="form-group">
        <th class="new-meal-field"><%= form.label :end_time %></th>
        <td><%= form.time_select :end_time, {
          ampm: true,
          ignore_date: true
        } %></td>
      </div>
    </tr>
  </table>
    <div class="actions">
      <%= form.submit :class => "btn btn-primary" %>
    </div>
  <% end %>


</div>

app/views/meal_postings/edit.html.erb
<h1>Editing Meal Posting</h1>

<%= render 'form', meal_posting: @meal_posting %>

<%= link_to 'Show', @meal_posting %> |
<%= link_to 'Back', meal_postings_path %>

app/views/meal_postings/index.html.erb
<!-- Google Maps; on right hand side -->

<aside class="google-maps">

  <% if current_user_latitude %>
    <% theLatitude = current_user_latitude %>
    <% theLongitude = current_user_longitude %>

  <% else %>
    <% theAddress = "46 Spadina Avenue Toronto" %>
  <% end %>

    <div id="googleMap" data-user-latitude='<%=theLatitude%>' data-user-longitude='<%=theLongitude%>'></div>


    <div id="google-search">
        <%= form_tag user_location_path, :method => :put do %>
          <span class="form-group">
            <%= text_field_tag :address, nil, placeholder: "Location", class: "form-control", id: "location-form" %>
            <%= submit_tag 'Go', class: "btn btn-default" %>
          </span>
          <%= hidden_field :latitude, :change, value: false %>
          <%= hidden_field :longitude, :change, value: false %>
        <% end %>
    </div>
</aside>

<!-- Meals posted on left hand side -->
<section class="postings">

<!-- Then, all the meals -->
<div class="postings-list">

<% @meal_postings.each do |meal_posting| %>
  <!-- IF MEAL POSTING SERVINGS HITS 0, STOPS DISPLAYING IT ON HOME PAGE -->
  <% if meal_posting.servings >= 1 %>
    <div class="meal-div" data-address='<%=meal_posting.user.address%>' data-longitude=<%=meal_posting.user.longitude%> data-latitude=<%=meal_posting.user.latitude%>>
    <!-- Image -->
      <div class="media">
        <span class="media-left">
          <%= cl_image_tag(meal_posting.image, class: 'media-object') %>
        </span>


        <span class="media-body">
          <div class="container-fluid media-container">

            <!-- Title, meal time(s), cost -->
            <div class="row row-heading">
              <br>
              <div class="col-xs-8">
                <b class="title"><%= meal_posting.title %></b>
              </div>

              <div class="col-xs-4">
                Cost: $<%= meal_posting.cost %>
              </div>
            </div>

            <!-- Description -->
            <div class="row row-body">
              <div class="col-xs-8">
                <% if meal_posting.end_time %>
                  Serving from: <%= meal_posting.base_time.strftime("%I:%M %p") %> - <%= meal_posting.end_time.strftime("%I:%M %p") %>
                <% else %>
                  Serving at: <%= meal_posting.base_time.strftime("%I:%M %p") %>
                <% end %>
              </div>
              <div class="col-xs-8">
                Date: <%= meal_posting.date.to_date() %>
              </div>
              <div class="col-xs-4">
                Servings Left: <%= meal_posting.servings %>
              </div>
              <br>

            </div>
            <!-- Servings left, allergy notices -->
            <div class="row row-footer">
              <div class="col-xs-8 marker-space">
                <div class="marker-circle col-xs-4">A</div>
                <div class="address"><%=meal_posting.user.address%></div>
              </div>
              <div class="col-xs-4">
                <!-- <button type="button" class="btn btn-primary">Order Info</button> -->
                <%= button_to "Order Info", meal_posting_path(meal_posting), class: "btn btn-warning order-info", method: "get" %>
              </div>
            </div>

          </div>
        </span>

      </div>
    </div>
  <% end %>

<% end %>

</div>

</section>

<script type="text/javascript">

  if(window.google) {
    initialize()
    locationSearch()
  } else {
    $.ajax("https://maps.googleapis.com/maps/api/js?key=AIzaSyBHyW__uRnMTsXjGPv54cP5Tli4MhL_vOA&callback=initialize", {
        crossDomain: true,
        dataType: 'script'
    })
    locationSearch()
  }
</script>

app/views/meal_postings/meal_posting_reviews.html.erb
<div class="container">
  <div class="row">
<h2><%= @meal_posting.title %> by <%=@meal_posting.user.name%></h2>
    <div class="row meal-div">
      <div class="col-xs-4 col-sm-3 col-md-3 meal-rating-img-div">
        <%= cl_image_tag(@meal_posting.image, class: 'circle img-thumbnail img-box') %>
      </div>
      <div class="col-xs-4 col-sm-9 col-md-9">
        <h4></h4>
        <div class="list-group-item meal-post-desc">
          <p>Description: <%= @meal_posting.description %><br/><br/>Allergy Notice: <%= @meal_posting.allergy_notice %></p>
        </div>
        <div class="row">
          <div class="col-sm-3 meal-posting-bottom-info">
            <p>
              <% if @meal_posting.end_time %>
                Serving from: <%= @meal_posting.base_time.strftime("%I:%M %p") %> - <%= @meal_posting.end_time.strftime("%I:%M %p") %>
              <% else %>
                Serving at: <%= @meal_posting.base_time.strftime("%I:%M %p") %>
              <% end %>
            </p>
          </div>
          <div class="col-sm-2 meal-posting-bottom-info">
            <p>Price: $<%= @meal_posting.cost %></p>
          </div>
          <div class="col-sm-3 meal-posting-bottom-info">
            <p>Servings Available: <%= @meal_posting.servings %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<hr class="user-meal-posting-separate">

<div class="container meal-rating-container">
  <% if @meal_posting.meal_ratings.any? %>
    <h2>Reviews: </h2>
    <table class = "table table-bordered review-table">
      <thead>
        <tr>
          <th class="review-rating">Rating</th>
          <th class="review-comment">Comment</th>
        </tr>
      </thead>
      <tbody>
        <% @meal_posting.meal_ratings.reverse.each do |review| %>
          <tr>
            <td class="review-rating"><%= review.rating %> / 10</td>
            <td class="review-comment"><%= review.comment %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
    <% if current_user %>
      <% @meal_posting.reservations.each do |reservation| %>
        <% if reservation.user_id === current_user.id && reservation.paid %>
            <h2>Add a review:</h2>

            <% flash.each do |key, value| %>
              <div class="<%= flash_class(key) %> flash-msg">
                <h3>~ERROR: <%= value %>~</h3>
              </div>
            <% end %>

          <%= form_for [@meal_posting, @review] do |f| %>
            <%= f.hidden_field :user_id,  value: current_user.id %>
            <dt>Comment: </dt>
            <dd><%= f.text_area :comment, class: "user-review-text" %></dd>
            <dt>Rating: <%= f.select :rating, [10, 9, 8, 7, 6, 5, 4, 3, 2, 1] %></dt>
            <dd class="submit"><%= f.submit "Submit", class: "btn btn-warning submit-user-review" %></dd>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <br>
    <%= button_to 'Back', meal_posting_path(@meal_posting), method: "get", class: "btn btn-warning"  %>
</div>

app/views/meal_postings/new.html.erb
<h2 class="new-meal-header">New Meal Posting</h2>

<%= render 'form', meal_posting: @meal_posting %>

<div class="container back-btn-container">
  <%= link_to 'Back', meal_postings_path, class: "btn btn-primary back-btn" %>
</div>

app/views/meal_postings/show.html.erb
<%= javascript_include_tag 'meal_postings' %>

<!-- User information at top of page -->
<div class=" meal-posting-user-info">
  <div class="row">
    <div class="row">
      <div class="col-xs-4 col-sm-3 col-md-3 profile-img-holder">
        <%= cl_image_tag(@user.image, class: 'circle img-box profile-pic') %>
      </div >
      <div class="profile-info" id="show-meals">
        <h3>User Information: </h3>
        <p>Name: <%= @user.name %></p>
        <p>Address: <%= @user.address %></p>
        <p>Phone: <%= @user.phone_number %></p>
        <p>Email: <%= @user.email %></p>
        <%= link_to 'Reviews', user_path(@user), :class => "btn btn-warning btn-md user-reviews-btn" %>
      </div>
    </div>
  </div>
</div>

<!-- Separation from User info to Meal Postings -->
<hr class="user-meal-posting-separate">

<!-- Shows as many meal postings as the user currently has -->
<div class="container">
  <div class="row">
    <% @ordered_meal_ids.each do |meal_id| %>
    <% meal_posting = @usermeals.find(meal_id) %>
    <div class="row meal-div meal-div-mealpostings-show">
      <div class="col-xs-4 col-sm-3 col-md-3 meal-posting-meal-images">
        <% if meal_posting.image %>
          <%= cl_image_tag(meal_posting.image, class: 'circle img-thumbnail img-box') %>
        <% end %>
      </div>
      <div class="col-xs-4 col-sm-9 col-md-9">
        <h4><%= meal_posting.title %></h4>
        <div class="list-group-item meal-post-desc">
          <p>Description: <%= meal_posting.description %><br/><br/>Allergy Notice: <%= meal_posting.allergy_notice %></p>
        </div>

        <div class="row">
          <div class="col-sm-3 meal-posting-bottom-info">
            <p>Date: <%= meal_posting.date.to_date() %></p>
          </div>
          <div class="col-sm-4 meal-posting-bottom-info">
            <p>
              <% if meal_posting.end_time %>
                Serving from: <%= meal_posting.base_time.strftime("%I:%M %p") %> - <%= meal_posting.end_time.strftime("%I:%M %p") %>
              <% else %>
                Serving at: <%= meal_posting.base_time.strftime("%I:%M %p")%>
              <% end %>
            </p>
          </div>
          <div class="col-sm-2 meal-posting-bottom-info">
            <p>Price: $<%= meal_posting.cost %></p>
          </div>
          <div class="col-sm-3 meal-posting-bottom-info">
            <p>Servings Available: <%= meal_posting.servings %></p>
          </div>
          <div class="review-button">
            <%= button_to 'Reviews', meal_posting_reviews_path(meal_posting), :method => :get, :class => "btn btn-warning btn-md meal-reviews-btn" %>
          </div>

          <% if current_user and current_user.id == meal_posting.user_id %>
          <div class="delete-button">
            <%= button_to 'Delete', meal_posting_path(meal_posting), :method => :delete, :class => "btn btn-warning btn-md meal-reviews-btn" %>
          </div>
          <% end %>
          <!-- Won't display reserve button if current user is the meal poster, or if there are no more servings -->
          <% if current_user and current_user.id != @user.id and meal_posting.servings >= 1 %>
          <!-- Reserving a meal opens a modal with a form -->
          <div class="reserve-button">
            <button type="button" class="btn btn-warning btn-md reserve" data-toggle="modal" data-target=".modal-<%=meal_posting.id%>">Reserve</button>
          </div>

          <% formID = meal_posting.id %>
          <!-- Modal -->
            <div class="modal fade modal-<%=formID%>" role="dialog">
              <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close-<%=formID%> close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Select Meal Options</h4>
                  </div>
                  <div class="modal-body">
                  <!-- Submission Form (local true means no ajax request) -->
                    <%= form_with(model: @reservation, remote: true, url: create_reservation_path, class: formID) do |form| %>
                      <% if @reservation.errors.any? %>
                        <div id="error_explanation">
                          <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this meal_posting from being saved:</h2>
                          <ul>
                          <% @reservation.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                          </ul>
                        </div>

                      <% end %>

                      <%= form.hidden_field :user_id, value: current_user.id %>
                      <%= form.hidden_field :meal_posting_id, value: meal_posting.id %>

                      <!-- http://api.rubyonrails.org/ search "text_field" for format -->
                      <!-- ActionView::Helpers::FormBuilder (search "form") -->
                      <!-- text_field: object_name, attribute_name (key) -->
                      <table>
                        <tr class="modal-form-group">
                          <td><%= form.label :number_of_people %></td>
                          <td><%= form.number_field :number_of_people, id: :number_of_people %></td>
                        </tr>
                        <tr class="modal-form-group">
                          <td><%= form.label :allergies %></td>
                          <td><%= form.text_field :allergies, id: :allergies %></td>
                        </tr>
                        <tr class="modal-form-group">
                          <td><b>Date:</b></td>
                          <td><%= meal_posting.date%></td>
                        </tr>
                        <% if meal_posting.end_time %>
                        <tr class="modal-form-group">
                          <td><%= form.label :reservation_time %></td>
                            <td><%= form.time_select :time,
                            {
                              start_hour: meal_posting.base_time.strftime("%H").to_i,
                              end_hour: meal_posting.end_time.strftime("%H").to_i,
                              ampm: true,
                              ignore_date: true
                            } %></td>
                        </tr>
                        <% else %>
                          <tr class="modal-form-group">
                            <td><b>Time</b></td>
                            <td><%= meal_posting.base_time.strftime("%I:%M %p")%></td>
                          </tr>
                          <%= form.hidden_field :time, value: meal_posting.base_time %>
                        <% end %>
                      </table>
                      <div class="modal-footer">
                        <%= form.submit "Submit", class: "btn btn-warning btn-md modal-reserve submit-"+formID.to_s %>
                        <button type="button" class="action btn btn-default modal-close close-<%=formID%>" data-dismiss="modal">Close</button>
                      </div>
                      <div class="messages-<%=formID%>"></div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>

        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="meal-postings"></div>