config/routes.rb
Rails.application.routes.draw do

  root to: "meal_postings#index"

  resources :users, except: [:index] do
    resources :meal_postings
    resources :user_ratings, except: [:show, :edit]
  end

  resources :meal_postings do
    resources :categories, only: [:show]
    resources :reservations
    resources :meal_ratings, except: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # COMMENTED OUT FOR NOW #
    # get '/login', to: 'posting#index'

    resources :postings, only: [:index, :new, :create]


    # CREATED FOR SESSIONS
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
    put '/user/location' => 'sessions#update'

    # CREATED FOR MEAL POSTING CATEGORIES
    put '/meal_postings/categories/:id' => 'meal_postings#category', :as => :meals_category

    # CREATED TO SHOW HOSTS / USERS THEIR CURRENT RESERVATIONS / REQUESTS
    get '/reservations' => 'reservations#index'#, :as => :user_reservations
    #CREATED TO SHOW HOSTS THEIR RESERVATIONS TO OTHER HOSTS
    get '/reservations/outgoing' => 'reservations#outgoingreservations'
    #TO CHANGE TO ACCEPTED / REJECTED
    put '/reservations/:id/accept' => 'reservations#accept'
    put '/reservations/:id/reject' => 'reservations#reject'

    ############## FOR hostdelete and userdelete ###############
    put '/reservations/:id/hostdelete' => 'reservations#hostdelete'
    put '/reservations/:id/userdelete' => 'reservations#userdelete'
    put '/reservations/outgoing/:id/userdelete' => 'reservations#userdelete'

    delete 'reservations/:id/destroy' => 'reservations#destroy'
    put '/reservations/:id/order' => 'reservations#order', :as => :reservation_order

    # TO CREATE A NEW RESERVATION
    post '/reservations/create/:id' => 'reservations#create', :as => :create_reservation

    # CREATED FOR A MEALPOSTING REVIEWS
    get '/meal_posting/:id/reviews' => 'meal_postings#meal_posting_reviews', :as => :meal_posting_reviews

    # CREATED FOR ANALYTICS
    get '/analytics' => 'analytics#index', :as => :analytics
end

app/models/meal_rating.rb
class MealRating < ApplicationRecord

  validates :comment, presence: true

  belongs_to :meal_posting
  belongs_to :user
end

app/controllers/meal_ratings_controller.rb
class MealRatingsController < ApplicationController
  before_action :set_meal_rating, only: [:show, :edit, :update, :destroy]

  # GET /meal_ratings
  # GET /meal_ratings.json
  def index
    @meal_ratings = MealRating.all
  end

  # GET /meal_ratings/new
  def new
    @meal_rating = MealRating.new
  end


  # POST /meal_ratings
  # POST /meal_ratings.json
  def create

    @meal_rating = MealRating.new(meal_rating_params)
    @meal_posting = MealPosting.find(params[:meal_posting_id])
    @meal_rating.meal_posting_id = params[:meal_posting_id]
    if @meal_rating.save
      redirect_to meal_posting_reviews_path(@meal_posting)

    else
      flash[:alert] = "Must include a comment"
      redirect_to meal_posting_reviews_path(@meal_posting)
    end
  end

  # DELETE /meal_ratings/1
  # DELETE /meal_ratings/1.json
  def destroy
    @meal_rating.destroy
    respond_to do |format|
      format.html { redirect_to meal_ratings_url }#, notice: 'Meal rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal_rating
      @meal_rating = MealRating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_rating_params
      params.require(:meal_rating).permit(:meal_posting_id, :user_id, :comment, :rating)
    end
end

app/helpers/meal_ratings_helper.rb
module MealRatingsHelper
end

app/views/meal_ratings/edit.html.erb
<h1>Editing Meal Rating</h1>

<%= render 'form', meal_rating: @meal_rating %>

<%= link_to 'Show', @meal_rating %> |
<%= link_to 'Back', meal_ratings_path %>

app/views/meal_ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meal Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Meal posting</th>
      <th>User</th>
      <th>Comment</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meal_ratings.each do |meal_rating| %>
      <tr>
        <td><%= meal_rating.meal_posting_id %></td>
        <td><%= meal_rating.user_id %></td>
        <td><%= meal_rating.comment %></td>
        <td><%= meal_rating.rating %></td>
        <td><%= link_to 'Show', meal_rating %></td>
        <td><%= link_to 'Edit', edit_meal_rating_path(meal_rating) %></td>
        <td><%= link_to 'Destroy', meal_rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal Rating', new_meal_rating_path %>

app/views/meal_ratings/new.html.erb
<h1>New Meal Rating</h1>

<%= render 'form', meal_rating: @meal_rating %>

<%= link_to 'Back', meal_ratings_path %>

app/views/meal_ratings/show.html.erb
<p>
  <strong>Meal posting:</strong>
  <%= @meal_rating.meal_posting_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @meal_rating.user_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @meal_rating.comment %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @meal_rating.rating %>
</p>

<%= link_to 'Edit', edit_meal_posting_meal_rating_path(@meal_rating) %> |