config/routes.rb
Rails.application.routes.draw do

  root to: "meal_postings#index"

  resources :users, except: [:index] do
    resources :meal_postings
    resources :user_ratings, except: [:show, :edit]
  end

  resources :meal_postings do
    resources :categories, only: [:show]
    resources :reservations
    resources :meal_ratings, except: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # COMMENTED OUT FOR NOW #
    # get '/login', to: 'posting#index'

    resources :postings, only: [:index, :new, :create]


    # CREATED FOR SESSIONS
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
    put '/user/location' => 'sessions#update'

    # CREATED FOR MEAL POSTING CATEGORIES
    put '/meal_postings/categories/:id' => 'meal_postings#category', :as => :meals_category

    # CREATED TO SHOW HOSTS / USERS THEIR CURRENT RESERVATIONS / REQUESTS
    get '/reservations' => 'reservations#index'#, :as => :user_reservations
    #CREATED TO SHOW HOSTS THEIR RESERVATIONS TO OTHER HOSTS
    get '/reservations/outgoing' => 'reservations#outgoingreservations'
    #TO CHANGE TO ACCEPTED / REJECTED
    put '/reservations/:id/accept' => 'reservations#accept'
    put '/reservations/:id/reject' => 'reservations#reject'

    ############## FOR hostdelete and userdelete ###############
    put '/reservations/:id/hostdelete' => 'reservations#hostdelete'
    put '/reservations/:id/userdelete' => 'reservations#userdelete'
    put '/reservations/outgoing/:id/userdelete' => 'reservations#userdelete'

    delete 'reservations/:id/destroy' => 'reservations#destroy'
    put '/reservations/:id/order' => 'reservations#order', :as => :reservation_order

    # TO CREATE A NEW RESERVATION
    post '/reservations/create/:id' => 'reservations#create', :as => :create_reservation

    # CREATED FOR A MEALPOSTING REVIEWS
    get '/meal_posting/:id/reviews' => 'meal_postings#meal_posting_reviews', :as => :meal_posting_reviews

    # CREATED FOR ANALYTICS
    get '/analytics' => 'analytics#index', :as => :analytics
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :image

  mount_uploader :image, AvatarUploader

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :phone_number, presence: true
  validates :password, presence: true, length: { minimum: 5 }
  validates :password_confirmation, presence: true
  validates :password_digest, presence: true
  validate :requires_proper_address

  def requires_proper_address
    if address == ""
        errors.add(:address, "must be valid")
    end
  end

  # Changes email to lower case before saving to database
  before_save :downcase_email
  def downcase_email
    self.email.downcase!
  end

  has_secure_password

  has_many :user_ratings
  has_many :meal_postings
  has_many :meal_ratings
  has_many :reservations
  # Allows the user_show page to access ratings by ratee_id
  has_many :received_ratings, foreign_key: "ratee_id", class_name: "UserRating"

  # Authentication function to check user details on login
  def self.authenticate_with_credentials(email, password)
    email.strip!
    email.downcase!
    user = find_by_email(email)
    if user && user.authenticate(password)
      user
    else
      nil
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @firstmeal = MealPosting.where("user_id = ?", @user.id).first
    if @firstmeal
      @firstmeal = @firstmeal.id
    end
    @review = UserRating.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # This is another way to upload images (or video), in case its needed later.
        # Though it won't save to the database.
        # Cloudinary::Uploader.upload(params[:user][:image])

        # Setting cookie to recognize logged in user
        session[:user_id] = @user.id
        session[:user_latitude] = @user.latitude
        session[:user_longitude] = @user.longitude
        format.html { redirect_to root_path }#, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }#, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }#, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params

      # REMOVED :password_digest and added :password and :password_confirmation
      params.require(:user).permit(
        :user_status,
        :address,
        :name,
        :email,
        :phone_number,
        :image,
        :password,
        :password_confirmation,
        :longitude,
        :latitude
        )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_editform.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "User Status: " %>
    <%= form.select :user_status, ['User', 'Host'], id: :user_user_status %>
  </div>

  <div class="field">
    <%= form.label "Address: " %>
    <%= form.text_field :address, id: :user_address %>
  </div>

  <div class="field">
    <%= form.label "Name: " %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label "Email: " %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label "Phone Number: " %>
    <%= form.text_field :phone_number, id: :user_phone_number %>
  </div>

  <div class="field">
    <%= form.label "Image: " %>
    <%= form.text_field :image, id: :user_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="user-register">
  <%= form_with(model: user, local: true, :html => { :multipart => true, :id => "register-form" }) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>

    <% end %>

    <table class="register-table">
      <tr>
        <div class="form-group">
          <th class="register-field"><%= form.label "User Status: " %></th>
          <td><%= form.select :user_status, ['User', 'Host'], id: :user_user_status %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th class="register-field"><%= form.label "Name: " %></th>
          <td><%= form.text_field :name, id: :user_name %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th class="register-field"><%= form.label "Email: " %></th>
          <td><%= form.text_field :email, id: :user_email %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th class="register-field"><%= form.label "Address: " %></th>
          <td><%= form.text_field :address, id: :user_address %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th class="register-field"><%= form.label "Phone Number: " %></th>
          <td><%= form.text_field :phone_number, id: :user_phone_number %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th class="register-field"><%= form.label "Image: " %></th>
          <td><%= form.file_field :image, id: :user_image %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th class="register-field"><%= form.label "Password: " %></th>
          <!-- Changed below to work with password_digest -->
          <td><%= form.password_field(:password, {id: :user_password}) %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th class="register-field"><%= form.label "Password Confirm: " %></th>
          <!-- Changed below to work with password_digest -->
          <td><%= form.password_field(:password_confirmation, {id: :user_password_confirmation}) %></td>
        </div>
      </tr>
      <%= form.hidden_field(:latitude, {id: :latitude, value: ""}) %>
      <%= form.hidden_field(:longitude, {id: :longitude, value: ""}) %>
    </table>
    <div class="actions">
      <%= form.submit class: 'new-user-submit btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit User Profile</h1>

<%= render 'editform', user: @user %>

<%= link_to 'Show', @user %> |

<!-- Now Links back to the SHOW for the user -->
<%= link_to 'Back', user_path(@user) %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>User status</th>
      <th>Address</th>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Phone number</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_status %></td>
        <td><%= user.address %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.image %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h2 class="new-user-header">Sign Up</h2>



<%= render 'form', user: @user %>

<!-- Now Links back to the Home/Root -->
<div class="back-button" ><%= link_to 'Back', root_path, class: "btn btn-primary" %></div>



<script type="text/javascript">
  if(! window.google) {
    $.ajax("https://maps.googleapis.com/maps/api/js?key=AIzaSyBHyW__uRnMTsXjGPv54cP5Tli4MhL_vOA&callback=watchRegister", {
        crossDomain: true,
        dataType: 'script'
    })
  } else {
    watchRegister()
  }
</script>

app/views/users/show.html.erb
<body>
  <!-- User information at top of page -->
  <div class=" meal-posting-user-info show-page">
    <div class="row col-xs-4 col-sm-3 col-md-3 profile-img-holder">
          <%= cl_image_tag(@user.image, class: 'circle img-box profile-pic') %>
    </div >
      <div class="profile-info">
        <h1><strong><%= @user.user_status%> Information: </strong></h1>
        <h3><strong>Name: <%= @user.name %></strong></h3>
        <h3><strong>Address: <%= @user.address %></strong></h3>
        <h3><strong>Phone: <%= @user.phone_number %></strong></h3>
        <h3><strong>Email: <%= @user.email %></strong></h3>
        <br/>
      </div>
    </div>

    <hr class="user-meal-posting-separate">

    <div class="container">
      <% if current_user === @user && current_user.user_status == "Host" %>
        <div class="new-meal-button">
          <%= button_to "Create a Meal", new_user_meal_posting_path(@user), :method => :get, :class => "btn btn-warning btn-md"%>
        </div>
        <% if @firstmeal %>
          <div class="view-meals-button">
            <%= button_to "View All Meals", meal_posting_path(@firstmeal), :method => :get, :id => @firstmeal, :class => "btn btn-danger btn-md"%>
          </div>
        <% end %>
      <% end %>
        <% if current_user and current_user.id != @user.id %>
          <h2>Add a review:</h2>
          <!-- Displays error messages if form submission is not correct -->
          <% flash.each do |key, value| %>
              <div class="<%= flash_class(key) %> flash-msg">
                <h3>~ERROR: <%= value %>~</h3>
              </div>
          <% end %>

          <%= form_for [@user, @review] do |f| %>
            <%= f.hidden_field :ratee_id,  value: @user.id %>
            <dt>Comment: </dt>
            <dd><%= f.text_area :comment, class: "user-review-text" %></dd>
            <dt>Rating: <%= f.select :rating, [10, 9, 8, 7, 6, 5, 4, 3, 2, 1] %></dt>
            <dd class="submit"><%= f.submit "Submit", class: "btn btn-warning submit-user-review" %></dd>
          <% end %>
        <% end %>

        <% if @user.received_ratings.any? %>

      <div class="user-reviews">
        <h2>Reviews: </h2>
        <table class = "table table-bordered review-table">
          <thead>
              <tr>
                <th class="review-rating">Rating</th>
                <th class="review-comment">Comment</th>
              </tr>
            </thead>
            <tbody>
              <% @user.received_ratings.reverse.each do |review| %>
                <tr>
                  <td class="review-rating"><%= review.rating %> / 10</td>
                  <td class="review-comment"><%= review.comment %></td>

                  <!-- IMPLEMENT DELETE BUTTON FOR COMMENTS HERE, ONLY IF CURRENT USER POSTED THE COMMENT -->
                  <% if current_user && review.user.id == current_user.id %>
                  <td><%= button_to 'Delete', { :controller => "user_ratings", :action => "destroy", user_id: current_user.id, id: review.id }, :method => :delete, :class => "btn btn-primary btn-md delete" %></td>
                  <% end %>
                </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <h3>No Reviews For This User</h3>
      <% end %>
    </div>
  </div>

</body>