config/routes.rb
Rails.application.routes.draw do

  root to: "meal_postings#index"

  resources :users, except: [:index] do
    resources :meal_postings
    resources :user_ratings, except: [:show, :edit]
  end

  resources :meal_postings do
    resources :categories, only: [:show]
    resources :reservations
    resources :meal_ratings, except: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # COMMENTED OUT FOR NOW #
    # get '/login', to: 'posting#index'

    resources :postings, only: [:index, :new, :create]


    # CREATED FOR SESSIONS
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
    put '/user/location' => 'sessions#update'

    # CREATED FOR MEAL POSTING CATEGORIES
    put '/meal_postings/categories/:id' => 'meal_postings#category', :as => :meals_category

    # CREATED TO SHOW HOSTS / USERS THEIR CURRENT RESERVATIONS / REQUESTS
    get '/reservations' => 'reservations#index'#, :as => :user_reservations
    #CREATED TO SHOW HOSTS THEIR RESERVATIONS TO OTHER HOSTS
    get '/reservations/outgoing' => 'reservations#outgoingreservations'
    #TO CHANGE TO ACCEPTED / REJECTED
    put '/reservations/:id/accept' => 'reservations#accept'
    put '/reservations/:id/reject' => 'reservations#reject'

    ############## FOR hostdelete and userdelete ###############
    put '/reservations/:id/hostdelete' => 'reservations#hostdelete'
    put '/reservations/:id/userdelete' => 'reservations#userdelete'
    put '/reservations/outgoing/:id/userdelete' => 'reservations#userdelete'

    delete 'reservations/:id/destroy' => 'reservations#destroy'
    put '/reservations/:id/order' => 'reservations#order', :as => :reservation_order

    # TO CREATE A NEW RESERVATION
    post '/reservations/create/:id' => 'reservations#create', :as => :create_reservation

    # CREATED FOR A MEALPOSTING REVIEWS
    get '/meal_posting/:id/reviews' => 'meal_postings#meal_posting_reviews', :as => :meal_posting_reviews

    # CREATED FOR ANALYTICS
    get '/analytics' => 'analytics#index', :as => :analytics
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :meal_postings
end

app/models/meal_posting.rb
class MealPosting < ApplicationRecord

  attr_accessor :image

  mount_uploader :image, AvatarUploader

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :meal_ratings
  has_many :media
  has_many :reservations

  validates :base_time, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :servings, presence: true, :numericality => { :greater_than => 0}
  validates :cost, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :date, presence: true
  validate  :end_time_cannot_be_earlier_than_start_time
  validate  :date_cannot_be_in_the_past

  def end_time_cannot_be_earlier_than_start_time

    if end_time
      if base_time > end_time
        errors.add(:end_time, "can't be earlier than the start time")
      end
    end
  end

  def date_cannot_be_in_the_past
    if date
      if date < Date.today
        errors.add(:date, "can't be set in the past")
      end
    end
  end
end

app/models/meal_rating.rb
class MealRating < ApplicationRecord

  validates :comment, presence: true

  belongs_to :meal_posting
  belongs_to :user
end

app/models/medium.rb
class Medium < ApplicationRecord

  attr_accessor :url

  mount_uploader :url, AvatarUploader

  belongs_to :meal_postings, optional: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :number_of_people, numericality: {greater_than: 0}
  validates :time, presence: true

  belongs_to :user
  belongs_to :meal_posting
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :image

  mount_uploader :image, AvatarUploader

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :phone_number, presence: true
  validates :password, presence: true, length: { minimum: 5 }
  validates :password_confirmation, presence: true
  validates :password_digest, presence: true
  validate :requires_proper_address

  def requires_proper_address
    if address == ""
        errors.add(:address, "must be valid")
    end
  end

  # Changes email to lower case before saving to database
  before_save :downcase_email
  def downcase_email
    self.email.downcase!
  end

  has_secure_password

  has_many :user_ratings
  has_many :meal_postings
  has_many :meal_ratings
  has_many :reservations
  # Allows the user_show page to access ratings by ratee_id
  has_many :received_ratings, foreign_key: "ratee_id", class_name: "UserRating"

  # Authentication function to check user details on login
  def self.authenticate_with_credentials(email, password)
    email.strip!
    email.downcase!
    user = find_by_email(email)
    if user && user.authenticate(password)
      user
    else
      nil
    end
  end

end

app/models/user_rating.rb
class UserRating < ApplicationRecord

  validates :comment, presence: true
  belongs_to :user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @firstmeal = MealPosting.where("user_id = ?", @user.id).first
    if @firstmeal
      @firstmeal = @firstmeal.id
    end
    @review = UserRating.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # This is another way to upload images (or video), in case its needed later.
        # Though it won't save to the database.
        # Cloudinary::Uploader.upload(params[:user][:image])

        # Setting cookie to recognize logged in user
        session[:user_id] = @user.id
        session[:user_latitude] = @user.latitude
        session[:user_longitude] = @user.longitude
        format.html { redirect_to root_path }#, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }#, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }#, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params

      # REMOVED :password_digest and added :password and :password_confirmation
      params.require(:user).permit(
        :user_status,
        :address,
        :name,
        :email,
        :phone_number,
        :image,
        :password,
        :password_confirmation,
        :longitude,
        :latitude
        )
    end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
      case level
          when :notice then "alert alert-info"
          when :success then "alert alert-success"
          when :error then "alert alert-error"
          when :alert then "alert alert-error"
      end
  end

end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/meal_ratings_helper.rb
module MealRatingsHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_ratings_helper.rb
module UserRatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_top_nav.html.erb
<!-- Navbar is fixed to the top of the page, even when scrolling -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="cat-link">
        <%= link_to analytics_path, class: "navbar-brand analytics cat-link" do %><span class="glyphicon glyphicon-eye-open"></span>Analytics<% end %>
      </div>
    </div>
    <ul class="nav navbar-nav navbar-left">


      <l1 class="cat-link"><a class="navbar-brand title-home" href="/" >HomeCooked</a></l1>
      <% if @categories %>
        <li class="dropdown">
          <a class="dropdown-toggle cat-list" data-toggle="dropdown" href="#">Categories
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to root_path, method: :get, class: "cat-list" do %>
                All
              <% end %>
            </li>
            <% @categories.each do |category| %>
              <li>
                <%= link_to meals_category_path(id: category.id), method: :put, class: "cat-list" do %>
                  <%= category.name %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      <% end %>
      <% if current_user && !current_page?(user_path(current_user)) %>
        <li class="cat-link"><%= link_to user_path(current_user) do %><span class="glyphicon glyphicon-home"></span> <%= current_user.name %> <% end %></li>
      <% end %>
      <% if current_user %>
        <li class="cat-link"><%= link_to reservations_path do %><span class="glyphicon glyphicon-list-alt"></span> Reservations <% end %></li>
      <% end %>
      <% if current_user %>
        <li class="cat-link"><%= link_to logout_path do %><span class="glyphicon glyphicon-log-out"></span> Logout <% end %></li>
      <% else %>
        <li class="cat-link"><%= link_to new_user_path do %><span class="glyphicon glyphicon-user"></span> Sign Up <% end %></li>
        <li class="cat-link"><%= link_to login_path do %><span class="glyphicon glyphicon-log-in"></span> Login <% end %></li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homecooked</title>

    <!-- Script used to generate pie charts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    <script src="https://leaverou.github.io/conic-gradient/conic-gradient.js"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- onload="initialize('200 spadina avenue toronto ontario')" -->

  </head>
  <body >
    <%= render 'layouts/top_nav' %>
    <%= yield %>
  </body >
</html>